export const ShopProductList = [
    {"id":1,"group":"Rims","title":"JAPAN RACING WHEELS - JR-25","picture":"assets/betashop/JAPAN RACING WHEELS - JR-25/1.png","sidePicture1":"assets/betashop/JAPAN RACING WHEELS - JR-25/2.png","sidePicture2":"assets/betashop/JAPAN RACING WHEELS - JR-25/3.png","description":"Japan Racing Wheels - JR-25 (18x8.5 inch)","price":29700,"detail":"Japan Racing Wheels - JR-25 (18x8.5 inch)"},
    {"id":2,"group":"Lights","title":"VLAND Full LED Tail Lights","picture":"assets/betashop/VLAND Full LED Tail Lights/1.png","sidePicture1":"assets/betashop/VLAND Full LED Tail Lights/2.png","sidePicture2":"assets/betashop/VLAND Full LED Tail Lights/3.png","description":"VLAND Full LED Tail Lights for Toyota 86 GT86 2012-2020 Subaru BRZ 2013-2020 Scion FR-S 2013-2020","price":26900,"detail":"VLAND Full LED Tail Lights for Toyota 86 GT86 2012-2020 Subaru BRZ 2013-2020 Scion FR-S 2013-2020"},
    {"id":3,"group":"Exhausts","title":"DNA MOTORING CBE-HC922-NRT","picture":"assets/betashop/DNA MOTORING CBE-HC922-NRT/1.png","sidePicture1":"assets/betashop/DNA MOTORING CBE-HC922-NRT/2.png","sidePicture2":"assets/betashop/DNA MOTORING CBE-HC922-NRT/3.png","description":"DNA MOTORING CBE-HC922-NRT Stainless Steel Cat Back Exhaust System [Compatible with 92-00 Honda Civic Coupe/Sedan]","price":11587,"detail":"DNA MOTORING CBE-HC922-NRT Stainless Steel Cat Back Exhaust System [Compatible with 92-00 Honda Civic Coupe/Sedan]"},
    {"id":4,"group":"Rims","title":"TOMASON TN24","picture":"assets/betashop/TOMASON TN24/1.png","sidePicture1":"assets/betashop/TOMASON TN24/2.png","sidePicture2":"assets/betashop/TOMASON TN24/3.png","description":"4x TOMASON TN24 Dark Hyperblack rim polished in 19 inches","price":1029.25,"detail":"4x TOMASON TN24 Dark Hyperblack rim polished in 19 inches"},
    {"id":5,"group":"Rims","title":"Savini BM14 Gloss Black","picture":"assets/betashop/Savini BM14 Gloss Black/1.png","sidePicture1":"","sidePicture2":"","description":"19 inch 19x8.5 Savini BM14 Gloss Black wheels rims 5x5 5x127 +15","price":1588.00,"detail":"19 inch 19x8.5 Savini BM14 Gloss Black wheels rims 5x5 5x127 +15"},
    {"id":6,"group":"Rims","title":"RONAL R71","picture":"assets/betashop/RONAL R71/1.png","sidePicture1":"assets/betashop/RONAL R71/2.png","sidePicture2":"assets/betashop/RONAL R71/3.png","description":"RONAL R71 ORBIT GREY MATT FRONTKOPIERT IN 20 INCH","price":1115,"detail":"RONAL R71 ORBIT GREY MATT FRONTKOPIERT IN 20 INCH"},
    {"id":7,"group":"Lights","title":"Headlights 3D LED","picture":"assets/betashop/Headlights 3D LED/1.png","sidePicture1":"assets/betashop/Headlights 3D LED/2.png","sidePicture2":"assets/betashop/Headlights 3D LED/3.png","description":"Headlights 3D LED DRL suitable for VW Golf 7 VII (2012-2017) Silver R-Line LED Flowing Dynamic Sequential Turning Lights","price":504.00,"detail":"Headlights 3D LED DRL suitable for VW Golf 7 VII (2012-2017) Silver R-Line LED Flowing Dynamic Sequential Turning Lights"},
    {"id":8,"group":"Rims","title":"BBS Super RS","picture":"assets/betashop/BBS Super RS/1.png","sidePicture1":"assets/betashop/BBS Super RS/2.png","sidePicture2":"assets/betashop/BBS Super RS/3.png","description":"BBS Super RS GOLD DIAMANTGEDREHT","price":7068.00 ,"detail":"BBS Super RS GOLD DIAMANTGEDREHT"},
    {"id":9,"group":"Lights","title":"Spyder Dodge Ram 1500","picture":"assets/betashop/Spyder Dodge Ram 1500/1.png","sidePicture1":"assets/betashop/Spyder Dodge Ram 1500/2.png","sidePicture2":"assets/betashop/Spyder Dodge Ram 1500/3.png","description":"Spyder Dodge Ram 1500 09-14 10-14 Projector Headlights Halogen- LED Halo LED - Blk PRO-YD-DR09-HL-BK 5010032","price":324.00,"detail":"Spyder Dodge Ram 1500 09-14 10-14 Projector Headlights Halogen- LED Halo LED - Blk PRO-YD-DR09-HL-BK 5010032"},
    {"id":10,"group":"Inside Parts","title":"Bosch Automotive Double Iridium Spark Plug","picture":"assets/betashop/Bosch Automotive Double Iridium Spark Plug/1.png","sidePicture1":"assets/betashop/Bosch Automotive Double Iridium Spark Plug/2.png","sidePicture2":"assets/betashop/Bosch Automotive Double Iridium Spark Plug/3.png","description":"Bosch Automotive Double Iridium Spark Plug, up to 4X Longer Life","price":48.33,"detail":"Bosch Automotive Double Iridium Spark Plug, up to 4X Longer Life"},
    {"id":11,"group":"Rims","title":"Platin P97","picture":"assets/betashop/Platin P97/1.png","sidePicture1":"assets/betashop/Platin P97/2.png","sidePicture2":"assets/betashop/Platin P97/3.png","description":"Platin P97 BLACK GLOSSY","price":5380,"detail":"Platin P97 BLACK GLOSSY"},
    {"id":12,"group":"Lights","title":"DNA Motoring HL-LB-HC01-BK-AM","picture":"assets/betashop/DNA Motoring HL-LB-HC01-BK-AM/1.png","sidePicture1":"assets/betashop/DNA Motoring HL-LB-HC01-BK-AM/2.png","sidePicture2":"assets/betashop/DNA Motoring HL-LB-HC01-BK-AM/3.png","description":"DNA Motoring HL-LB-HC01-BK-AM For 2001 to 2003 Honda Civic 2DR / 4DR LED DRL Light Bar Projector Headlight Black Housing Amber Side Headlamps 02","price":163.48,"detail":"DNA Motoring HL-LB-HC01-BK-AM For 2001 to 2003 Honda Civic 2DR / 4DR LED DRL Light Bar Projector Headlight Black Housing Amber Side Headlamps 02"},
    {"id":13,"group":"Inside Parts","title":"RIDEX 4G0143 Lichtmaschine","picture":"assets/betashop/RIDEX 4G0143 Lichtmaschine/1.png","sidePicture1":"assets/betashop/RIDEX 4G0143 Lichtmaschine/2.png","sidePicture2":"assets/betashop/RIDEX 4G0143 Lichtmaschine/3.png","description":"RIDEX 4G0143 Lichtmaschine 12V, 60A","price":120.57,"detail":"RIDEX 4G0143 Lichtmaschine 12V, 60A"},
    {"id":14,"group":"Lights","title":"FULL LED Headlight","picture":"assets/betashop/Customized FULL LED Headlight/1.png","sidePicture1":"assets/betashop/Customized FULL LED Headlight/2.png","sidePicture2":"assets/betashop/Customized FULL LED Headlight/3.png","description":"Customized FULL LED Headlight dual beam for 18-20 Mustang Left/ Driver Side","price":253.00,"detail":"Customized FULL LED Headlight dual beam for 18-20 Mustang Left/ Driver Side"},
    {"id":15,"group":"Rims","title":"Chrome Plated","picture":"assets/betashop/Chrome Plated/1.png","sidePicture1":"","sidePicture2":"","description":"Replica 161C Fits Hellcat 20x9 5x115 +20mm Chrome Wheel Rim 20 Inch","price":361.99,"detail":"Replica 161C Fits Hellcat 20x9 5x115 +20mm Chrome Wheel Rim 20 Inch"},
    {"id":16,"group":"Lights","title":"LED Headlights Dual Beam","picture":"assets/betashop/LED Headlights Dual Beam/1.png","sidePicture1":"","sidePicture2":"","description":"Customized LED Headlights Dual Beam w/ Sequential Turn Sig. for 13-16 Scion FR-S","price":388.55,"detail":"Customized LED Headlights Dual Beam w/ Sequential Turn Sig. for 13-16 Scion FR-S"}
];